apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    app: my-app
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80