apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: springboot-kubernetes
